1) Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [9]:
c=np.array([[1,3,6,7],[2,3,5,7]])
d=np.array([[0,5,1,9],[12,1,7,2]])

In [10]:
f=c+d

In [11]:
print(f)

[[ 1  8  7 16]
 [14  4 12  9]]


2) Write a Python Program to Multiply Two Matrices?

In [26]:
a=np.array([[2,1],[1,0]])
b=np.array([[1,0],[0,1]])
def mul_mat():
    mul_matrix=a.dot(b)
    print(mul_matrix)

In [27]:
mul_mat()

[[2 1]
 [1 0]]


3) Write a Python Program to Transpose a Matrix?


In [29]:
c=np.array([[1,3,6,7],[2,3,5,7]])

In [30]:
def tran_matrix():
    transpose_mat=c.transpose()
    print(transpose_mat)

In [32]:
tran_matrix()

[[1 2]
 [3 3]
 [6 5]
 [7 7]]


4) Write a Python Program to Sort Words in Alphabetic Order?


In [35]:
def sort_words():
    sentence=str(input("Enter the sentence"))
    words=sentence.split()
    #print(words)
    words.sort()
    for word in words:
        print(word)

In [36]:
sort_words()

Enter the sentenceI am Dattatreya Thunuguntla. Currently pursuing my M.Tech at NIT Jaipur & parallelly doing the FSDS course offered by iNeuron
&
Currently
Dattatreya
FSDS
I
Jaipur
M.Tech
NIT
Thunuguntla.
am
at
by
course
doing
iNeuron
my
offered
parallelly
pursuing
the


5) Write a Python Program to Remove Punctuation From a String?


In [39]:
def remove_punc():
    punctuations="!'"'#$%&"'"()*+,-./:;?@[\]^_`{|}~"
    sen=input("Enter the expression: ")
    modi_sen=""
    for char in sen:
        if char not in punctuations:
            modi_sen=modi_sen+char
    print(modi_sen)

In [40]:
remove_punc()

Enter the expression: Hello Buddy!!! Where are you going?
Hello Buddy Where are you going
